### ISSUE TITLE
Add a destroy method?

### ISSUE THREAD

**Issue by zhw2590582** [kamranahmedse/brusher#4]
Hi, I just want to use it to achieve multiple background image switching, Are you plan add a destroy method?

**Comment by masonwang025** [comment]
For anyone looking in the future: 
It doesn't need a destroy method; you can modify the source code of `loadSelectedImage()`.
Currently, it will not change the image if an image is already loaded (if `this.image` exists).
``` javascript
if (this.image) {
      return; // won't load image if already loaded
}
// code to load image
```
Simply add a conditional statement and possibly another function to change the image.
